#include<bits/stdc++.h>//this includes all the libraries..
#include <iostream>/// this is the only librairy gives the cin cout functions only..
using namespace std; // For avoinding the std so many times...
int main()// this is the main function which the begin from here execuetion..
{
   int x,y; //Intger type variable...
   cin >> x >> y;// This takes the input as for the x and y...
   cout << "Value of x: " << x << " and y: " << y;// this will gives the output which we take as input for the x and y..
    return 0; // this is the return 0 means their is no error... 
}